### ISSUE TITLE
Why does the README not look right on PyPI?

### ISSUE THREAD

**Issue by john-science** [john-science/exif_delete#6]
I use *very* standard markdown, which they say the support.

Hmmph

**Comment by theJollySin** [comment]
Okay, so apparently this has been fixed, but you need to do a little extra work:

https://stackoverflow.com/questions/26737222/how-to-make-pypi-description-markdown-work

Also, do I have "Natural Language" in the setup.py"

**Comment by john-science** [comment]
Well, laziness really won out here.  It looks like pypi.org made some updates that solved this issue for me. Harry!

https://pypi.org/project/exif-delete/
